buildscript {
    repositories {
        maven {
            name "JitPack"
            url "https://jitpack.io"
        }
        maven {
            name "Puzzles Releases"
            url "https://maven.puzzleshq.dev/releases/"
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        mavenLocal()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.gradleup.shadow:shadow-gradle-plugin:8.3.3"
        classpath("dev.puzzleshq:jigsaw-suite:$puzzle_jigsaw_suite")
    }
}

rootProject.name = 'Horizon Physics'

